// Every spoken line. tools/bake-voices.mjs turns each one into audio/<who>-<group>-<i>.mp3
// Add new lines at the END of a list: clip files are named by position.
window.LINES = {
  gary: {
    chatter: [
      'Item one. Review of item one.',
      'Moving on to item two. Which is also item one.',
      'Per my last email.',
      "Let's circle back to the agenda.",
      'I will now read the agenda. Again.',
      "Can we take this offline? We are offline. Let's take it more offline.",
      "Let's put a pin in that. And in this. Pins everywhere.",
      'Item three is a recap of items one and two. Item one.',
      "I'll share the deck after. There is no deck.",
      "Let's double click on that. Then single click. Then double click again.",
      'As per the agenda, which I am reading, and you are not.',
      "We'll take the rest async. Right now. Out loud.",
      'Can everyone go on mute. Except me. And Chad, apparently.',
      'Let us table this. And then un-table it. And then table it.',
      'Hard stop at the top of the hour. Of some hour.',
    ],
    cut: ['Sorry, let me stop you there.', "Let's park that.", 'Great point. Moving on.', "We're short on time.",
      "Let's take that offline.", "That's a great question for a different meeting.", "I'm going to stop you, for time."],
    yourTurn: ["Okay. Let's hear from you. You have the floor."],
    followup: ["Great meeting, everyone. Let's schedule a follow-up to discuss this meeting."],
  },
  chad: {
    chatter: [
      'Quick question, super quick, so basically going back to Q3, which ties into Q2, which honestly ties into Q1, which reminds me of a story.',
      'Just to piggyback on that, and on what I said before that, and before that.',
      'Sorry, go ahead. Actually, one more thing.',
      'Not to be that guy, but, and I am that guy.',
      'Love that. Love this. Love all of it. Quick question though.',
      "Sorry, I'm driving. Can you all hear me? I'm going into a tunnel. Still talking though.",
      'Big picture? Let me zoom out. Let me zoom out more. Okay, now I am in space.',
      "Hot take, but what if we just did what we said last week, but louder.",
      "I'm just thinking out loud here, for the next eleven minutes.",
      "Can we get a quick pulse check? Thumbs up. Okay, I'll take silence as a yes.",
      "Sorry, my dog. No, that was me. I'm excited.",
      "Ooh, let me play devil's advocate. And then angel's advocate. And then my own advocate.",
      "Real quick, does anyone know how to turn off this cat filter? I don't have a cat.",
      "I'd love to circle back on circling back.",
    ],
    cut: ['Oh, real quick!', 'Sorry, sorry, just jumping in!', 'Ooh, can I add to that?', "Before you finish, which you won't!",
      'Wait, wait, wait, wait, wait!', "Yes! And! Also! Me!", "Sorry, you cut out. So anyway, me!"],
    share: ['Can everyone see my screen? Can you see it now? How about now?'],
    shareEnd: ['Okay, so that was the wrong tab. Anyway.'],
    skip: ["Okay, I'll go then."],
  },
  tina: {
    chatter: ['Yeah, no, totally.', 'Totally. Yeah. No.', 'No, yeah, a hundred percent.', 'Yes. Agreed. With everyone. Always.', 'Mm-hm. Mm-hm. Yeah, no.',
      'Yeah. No. Yeah. Sorry, which one did I say?', 'Plus one. Plus two. Plus one to my plus one.', 'Oh, for sure, for sure, for sure.',
      'Love that for us.', 'No, totally, I was going to say the exact same thing. Word for word. Which was. Yeah.', 'Agreed! Wait. What did we agree on? Agreed.',
      'Sorry, I was on mute. I said yeah.'],
    cut: ['Yeah, no, totally!', 'Totally, yeah, but no, but yeah!', "Agreed, with whoever's talking!", 'Oh my gosh, same!', 'Yes! What they said! Not you. Them!'],
  },
  bot: {
    join: ["Hello. I am Gary's AI notetaker. This meeting is being recorded."],
    chatter: ['Summary so far: nothing.', 'Action item detected. Action item deleted.', 'Chad has said forty percent of all words.',
      'Chad is now at sixty percent of all words.', 'Sentiment analysis: everyone agrees. Nobody knows with what.', 'Note to self: the user has not spoken. Marking user as a plant.',
      'Updating minutes. Minutes: many.', 'Detected the word synergy. Increasing synergy.'],
    cut: ['Your audio is unclear. Please stop.', 'Background noise detected. The background noise is you.'],
    end: ['Sorry. We are at time.'],
  },
  you: {
    cut: ['So I just wanted to—', 'Sorry, can I just—', 'Quick thing, I think we sh—', 'Hi, hello, I—', 'Sor—', 'I—',
      'Could I just quickly—', 'Sorry, to go back to—', 'Can everyone hear m—', 'Okay so, about my—'],
    final: ['Okay! So. I think the main thing is—'],
  },
};
